### ISSUE TITLE
另一个获取原始地址的办法

### ISSUE THREAD

**Issue by cnbeining** [Vespa314/bilibili-api#1]
https://github.com/cnbeining/Biligrab/blob/master/biligrab.py#L265

然后跳到

https://github.com/cnbeining/Biligrab/blob/master/biligrab.py#L471

（是的，这个是Biligrab的本体。。。）

至于解析，

https://github.com/cnbeining/Biligrab/blob/master/biligrab.py#L157

我不厚道了。但是好使。

（如果你对于非API比较吃心，Flvxz有个漂亮的API。但是我觉得没有意义，就不弄了。）

这个适用于原始源是sina的，但是被二压备份的情况。可以保证更好的画质。

**Comment by kuniasahi** [comment]
腾讯源和新浪源都可以获取得到吗？

**Comment by cnbeining** [comment]
理论上适用任何源。

**Comment by cnbeining** [comment]
Flvxz理论上不开放API了，我close掉。

喜欢的的私下戳我研究，为了安全，不想太公开。
