### ISSUE TITLE
bilibili.py 获取评论失效

### ISSUE THREAD

**Issue by TimeCompass** [Vespa314/bilibili-api#12]
python首先给我报了个错告诉我bilibili.py 184行的ver未定义然后看了看api.md…………漏改了代码？
于是去掉了GetComment()的ver=ver，嗯，能用了（why?）
随后发现最新的视频并不能抓到评论数据
不严格的二分法发现avid=3280075之后的评论不能直接抓取
举例
http://api.bilibili.cn/feedback?aid=3280082 ← {"totalResult":0,"pages":0}
http://api.bilibili.cn/feedback?aid=3280082&ver=3 ← ver=3后能返回数据

然后往后试了下其他avid
http://api.bilibili.cn/feedback?aid=4232083 ← No
http://api.bilibili.cn/feedback?aid=4232083&ver=3 ← Yes

再往前试了下
http://api.bilibili.cn/feedback?aid=2053 ← Yes
http://api.bilibili.cn/feedback?aid=2053&ver=3 ← Yes

看来世界需要ver=3 _(:3」∠)_

**Comment by TimeCompass** [comment]
补充：
自己重新写了个轮子来抓评论然后发现ver3并没有pagesize（或者改成其他参数名了）

**Comment by Vespa314** [comment]
嗯，好像是的，不过ver=2还是3效果好像都是一样的，拉回来都是热门评论，没找到非热门评论的拉去方法；

所以搞了一个新接口：GetComment_v2，从http://api.bilibili.com/x/reply那里拉数据，貌似信息更丰富。。不过也没找到设置pagesize的方法，所以数量大的话拉起来比较慢。。

**Comment by TimeCompass** [comment]
等待回复的期间因为看不懂class那部分修改无力于是完全重新造了个轮子（和车）先用起来了 _(:3」∠)_
https://github.com/TimeCompass/bilibili-antispam/blob/master/antispam.py
