### ISSUE TITLE
获取直播间状态的API的地址是否有误？

### ISSUE THREAD

**Issue by CKylinMC** [Vespa314/bilibili-api#14]
## 见api.md

**获取开通直播状态**
- URL：【返回json】
  - `http://space.bilibili.com/ajax/live/getLive?`
- 输入：
  - mid：用户id
- 返回格式：
  - status：true or false，是否开通直播
  - data：如果开通，为直播房间号
    #### API实现：

``` python
HasLiving(mid)
```

**当前是否在直播**
- URL：【返回json】
  - `http://space.bilibili.com/ajax/live/getLive?`
- 输入：
  - mid：用户id
- 返回格式：
  - 第一层：data
    - 第二层：
      - url：地址
      - title：房间名
      - cover：封面
#### API实现：

``` python
IsLiving(mid)
```

---

这两个API的URL一样？
如果是的话第二个好像不会返回第二层，会返回和第一个API一样的内容= =
是我打开方式不对吗

**Comment by Cansll** [comment]
看py里的代码地址好像该是
http://live.bilibili.com/bili/isliving/

**Comment by Cansll** [comment]
点错0.0
