### ISSUE TITLE
首页文档拼写错误

### ISSUE THREAD

**Issue by fcym97** [Vespa314/bilibili-api#3]
bilibili-vedio/:爬取B站所有视频信息【已完成，数据暂不公开】
//此处应为video

**Comment by cnbeining** [comment]
为什么要揭穿

你知道我们已经忍了多少年了么。。。。。。

**Comment by fcym97** [comment]
强迫症表示不能忍

**Comment by Vespa314** [comment]
好吧，虽然早就发现了，但是懒得改，既然有人这么说。。那就彻底大替换吧23333
