### ISSUE TITLE
关于GetVideoUrl

### ISSUE THREAD

**Issue by drizztxx** [Vespa314/bilibili-api#6]
Hi,

首先感谢作者做出如此出色的项目!

最近想把B站上的某部新番下到本地，刚好发现这个项目，貌似调用这个函数可以直接获取下载链接。

我试了下，确实成功了，下载链接是http://cn-zjcz7-dx.acgvideo.com/xxxx 这种形式的。现在有个小问题：我把链接直接复制到浏览器里下载是没有问题的，为什么在迅雷里下载会一直失败呢？我已经把迅雷设置为只从原始地址下载、单线程了啊。因为浏览器下载一直不太稳定，特来寻求帮助。

BR,

Drizzt

**Comment by cnbeining** [comment]
请发详细日志。

Beining

2015年10月3日星期六，drizztxx <notifications@github.com> 写道：

**Comment by drizztxx** [comment]
不好意思，并没有日志。

我是在windows系统下运行的：
python.exe bilidownload.py http://www.bilibili.com/video/av2954198 | clip

然后用迅雷下载粘贴板中的链接，一直下不了。。。

感谢回复！

**Comment by hanbang-wang** [comment]
用新的版本
